# Generated by Django 5.1.3 on 2024-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_alter_especialidad_options_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_fecha_hora',
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'especialidad'), name='unique_fecha_hora_especialidad'),
        ),
    ]
